motd:
  message: "Tezk's Plugin Development Shack"
  colourful: true
  colours:
    - 'RED'
    - 'BLUE'
    - 'GOLD'
    - 'DARK_BLUE'
    - 'DARK_RED'
    - 'WHITE'
    - 'YELLOW'
    - 'GREEN'
    - 'AQUA'
    - 'DARK_AQUA'
    - 'DARK_GREEN'
    - 'DARK_PURPLE'
login-message:
  - "Hello, and welcome &e%player%&f!"
  - "Checkout: &ehttps://www.mc-market.org/threads/659184/"
  - ""
disable-breaking:
  everyone: true
  enabled: true