name: TezkCore
main: me.tezk.tezkcore.TezkCore
author: Tezk
version: 1.0
api-version: 1.14
permissions:
  tezkcore.disablebreaking:
    description: Disable breaking of blocks
commands:
  speed:
    description: Sets player speed <1-5>
  tezkcore:
    description: Reload TezkCore configuration
  spawn:
    description: Teleport to world spawn